-- PostgreSQL test-account bootstrap for StealthSync.
-- Run with: psql -U postgres -d stealthsync -f scripts/init_data.sql

BEGIN;

CREATE TABLE IF NOT EXISTS user_accounts (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    recovery_phrase_hash VARCHAR(255),
    role VARCHAR(32) NOT NULL,
    is_subscribed BOOLEAN NOT NULL DEFAULT FALSE,
    is_suspended BOOLEAN NOT NULL DEFAULT FALSE,
    subscription_id BIGINT
);

INSERT INTO user_accounts (
    username,
    email,
    password_hash,
    recovery_phrase_hash,
    role,
    is_subscribed,
    is_suspended,
    subscription_id
) VALUES (
    'admin',
    'admin@stealthsync.com',
    '$2a$10$J8tlnHhHKhPc.6YYHnZu2.GO2RuoCGgk4kFx0VGp9Y4qR62ZONqr2',
    NULL,
    'admin',
    FALSE,
    FALSE,
    NULL
)
ON CONFLICT (username) DO UPDATE SET
    email = EXCLUDED.email,
    password_hash = EXCLUDED.password_hash,
    role = EXCLUDED.role,
    is_suspended = FALSE;

INSERT INTO user_accounts (
    username,
    email,
    password_hash,
    recovery_phrase_hash,
    role,
    is_subscribed,
    is_suspended,
    subscription_id
) VALUES (
    'testuser',
    'testuser@stealthsync.com',
    '$2a$10$/3geUgFrWZVN0hkak6tCuuDVoXfoAyA8WRurjOdGCXSlkzSrTGaGe',
    NULL,
    'customer',
    FALSE,
    FALSE,
    NULL
)
ON CONFLICT (username) DO UPDATE SET
    email = EXCLUDED.email,
    password_hash = EXCLUDED.password_hash,
    role = EXCLUDED.role,
    is_subscribed = FALSE,
    is_suspended = FALSE,
    subscription_id = NULL;

COMMIT;
